title: HPC Tutorials
email: marcc-help@marcc.jhu.edu
description: >-
  Basic HPC tutorials are under development at this site.
baseurl: ""
url: "/tutorials" #! not required for github pages?
github_username:  bradleyrp
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  tutorials:
    output: true
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
